controller_list:
  - name: fake_l_arm_controller
    joints:
      - l_shoulder_yaw_joint
      - l_shoulder_pitch_joint
      - l_shoulder_roll_joint
      - l_underarm_joint
      - l_elbow_pitch_joint
      - l_elbow_yaw_joint
      - l_wrist_pitch_joint
      - l_wrist_roll_joint
  - name: fake_r_arm_controller
    joints:
      - r_shoulder_yaw_joint
      - r_shoulder_pitch_joint
      - r_shoulder_roll_joint
      - r_underarm_joint
      - r_elbow_pitch_joint
      - r_elbow_yaw_joint
      - r_wrist_pitch_joint
      - r_wrist_roll_joint